import type { PropertyRow } from "@/types/database";

const baseDate = "2026-08-01T08:00:00.000Z";

export const demoProperties: PropertyRow[] = [
  {
    id: "11111111-1111-4111-8111-111111111111",
    reference_code: "TWR-1001",
    title: { en: "Ankawa Garden Villa", ku: "ڤێلای باخچەی عەنکاوا", ar: "فيلا حديقة عنكاوا" },
    description: {
      en: "A calm four-bedroom villa with a private garden, generous daylight and direct access to Ankawa's main services.",
      ku: "ڤێلایەکی ئارامی چوار ژوور، بە باخچەی تایبەت و ڕووناکی زۆر، نزیک خزمەتگوزارییە سەرەکییەکانی عەنکاوا.",
      ar: "فيلا هادئة من أربع غرف مع حديقة خاصة وإضاءة طبيعية وقرب مباشر من خدمات عنكاوا الرئيسية."
    },
    property_type: "house",
    status: "available",
    price: 385000,
    currency: "USD",
    area_m2: 420,
    address: "Ankawa, Erbil",
    latitude: 36.2307,
    longitude: 43.9955,
    location: null,
    image_url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=85",
    gallery: [],
    payment_options: ["cash", "installment"],
    completion_percent: 100,
    is_published: true,
    created_by: null,
    created_at: baseDate,
    updated_at: baseDate
  },
  {
    id: "22222222-2222-4222-8222-222222222222",
    reference_code: "TWR-1002",
    title: { en: "Empire Skyline Apartment", ku: "شوقەی ئاسمانی ئیمپایەر", ar: "شقة إطلالة إمباير" },
    description: {
      en: "A premium high-floor apartment with panoramic city views, secure parking and a refined open-plan interior.",
      ku: "شوقەیەکی نایابی نهۆمی بەرز بە دیمەنی پانۆرامای شار، پارکینگی پارێزراو و ناوەوەی مۆدێرن.",
      ar: "شقة فاخرة في طابق مرتفع بإطلالة بانورامية وموقف آمن وتصميم داخلي مفتوح."
    },
    property_type: "apartment",
    status: "available",
    price: 198000,
    currency: "USD",
    area_m2: 184,
    address: "Empire World, Erbil",
    latitude: 36.2093,
    longitude: 44.0361,
    location: null,
    image_url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1400&q=85",
    gallery: [],
    payment_options: ["cash", "installment", "advance"],
    completion_percent: 100,
    is_published: true,
    created_by: null,
    created_at: baseDate,
    updated_at: baseDate
  },
  {
    id: "33333333-3333-4333-8333-333333333333",
    reference_code: "TWR-1003",
    title: { en: "English Village Family Home", ku: "خانووی خێزانی ئینگلیش ڤیلەج", ar: "منزل عائلي في القرية الإنجليزية" },
    description: {
      en: "A finished family home with a private courtyard, quiet streets and practical access to schools and retail.",
      ku: "خانوویەکی تەواوکراوی خێزانی بە حەوشەی تایبەت، کۆڵانی ئارام و دەستگەیشتنی ئاسان بە قوتابخانە و بازاڕ.",
      ar: "منزل عائلي مكتمل مع فناء خاص وشوارع هادئة ووصول سهل إلى المدارس والأسواق."
    },
    property_type: "house",
    status: "reserved",
    price: 310000,
    currency: "USD",
    area_m2: 360,
    address: "English Village, Erbil",
    latitude: 36.1884,
    longitude: 44.0711,
    location: null,
    image_url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=85",
    gallery: [],
    payment_options: ["cash", "advance"],
    completion_percent: 100,
    is_published: true,
    created_by: null,
    created_at: baseDate,
    updated_at: baseDate
  },
  {
    id: "44444444-4444-4444-8444-444444444444",
    reference_code: "TWR-1004",
    title: { en: "Bakhtiary Corner Plot", ku: "زەوی سەرگۆشەی بەختیاری", ar: "قطعة زاوية في بختياري" },
    description: {
      en: "A well-proportioned corner parcel suited to a private residence or a compact residential development.",
      ku: "پارچە زەوییەکی سەرگۆشە و ڕێک بۆ خانووی تایبەت یان پڕۆژەیەکی بچوکی نیشتەجێبوون.",
      ar: "قطعة أرض زاوية متناسقة مناسبة لمنزل خاص أو مشروع سكني مدمج."
    },
    property_type: "land",
    status: "available",
    price: 265000,
    currency: "USD",
    area_m2: 500,
    address: "Bakhtiary, Erbil",
    latitude: 36.1966,
    longitude: 43.9572,
    location: null,
    image_url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1400&q=85",
    gallery: [],
    payment_options: ["cash"],
    completion_percent: 0,
    is_published: true,
    created_by: null,
    created_at: baseDate,
    updated_at: baseDate
  },
  {
    id: "55555555-5555-4555-8555-555555555555",
    reference_code: "TWR-1005",
    title: { en: "Gulan Residence", ku: "نیشتەجێبوونی گولان", ar: "سكن گولان" },
    description: {
      en: "A contemporary two-bedroom residence currently in its finishing stage with flexible installment terms.",
      ku: "شوقەیەکی هاوچەرخی دوو ژوور کە لە قۆناغی تەواوکاریدایە و مەرجی قیستی ئاسان هەیە.",
      ar: "شقة عصرية بغرفتين في مرحلة التشطيب مع شروط تقسيط مرنة."
    },
    property_type: "apartment",
    status: "construction",
    price: 142000,
    currency: "USD",
    area_m2: 136,
    address: "Gulan Street, Erbil",
    latitude: 36.2125,
    longitude: 44.0088,
    location: null,
    image_url: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=85",
    gallery: [],
    payment_options: ["installment", "advance"],
    completion_percent: 78,
    is_published: true,
    created_by: null,
    created_at: baseDate,
    updated_at: baseDate
  },
  {
    id: "66666666-6666-4666-8666-666666666666",
    reference_code: "TWR-1006",
    title: { en: "Dream City Duplex", ku: "دووپلێکسی دریم سیتی", ar: "دوبلكس دريم سيتي" },
    description: {
      en: "A light-filled duplex with a double-height living area, three bedrooms and carefully finished private terraces.",
      ku: "دووپلێکسێکی پڕ ڕووناکی بە هۆڵی بەرزی دوو نهۆم، سێ ژوور و تەڕاسی تایبەتی جوان.",
      ar: "دوبلكس مضيء بصالة مزدوجة الارتفاع وثلاث غرف نوم وتراسات خاصة بتشطيب دقيق."
    },
    property_type: "apartment",
    status: "sold",
    price: 245000,
    currency: "USD",
    area_m2: 218,
    address: "Dream City, Erbil",
    latitude: 36.2347,
    longitude: 44.0291,
    location: null,
    image_url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1400&q=85",
    gallery: [],
    payment_options: ["cash", "installment"],
    completion_percent: 100,
    is_published: true,
    created_by: null,
    created_at: baseDate,
    updated_at: baseDate
  }
];
